//! Serialization and accessor codegen for Phase 11.2–11.3.

use proc_macro2::{Ident, Span, TokenStream as TokenStream2};
use quote::quote;

// ── 11.2 Serialization ───────────────────────────────────────────────────────

/// Generate `Model::hidden / visible / appends` overrides.
pub fn gen_hidden_visible_appends(
    hidden:  &[String],
    visible: &[String],
    appends: &[String],
) -> TokenStream2 {
    let hidden_len  = hidden.len();
    let visible_len = visible.len();
    let appends_len = appends.len();

    let hidden_impl = if hidden_len > 0 {
        quote! {
            fn hidden() -> &'static [&'static str] {
                static H: [&str; #hidden_len] = [#(#hidden),*];
                &H
            }
        }
    } else { quote! {} };

    let visible_impl = if visible_len > 0 {
        quote! {
            fn visible() -> &'static [&'static str] {
                static V: [&str; #visible_len] = [#(#visible),*];
                &V
            }
        }
    } else { quote! {} };

    let appends_impl = if appends_len > 0 {
        quote! {
            fn appends() -> &'static [&'static str] {
                static A: [&str; #appends_len] = [#(#appends),*];
                &A
            }
        }
    } else { quote! {} };

    quote! { #hidden_impl #visible_impl #appends_impl }
}

/// Generate:
/// - `{Model}Appends` trait (one method per appended field)
/// - inherent `serialize()`, `make_visible()`, `make_hidden()` on the struct
pub fn gen_serialize_methods(
    struct_name:   &Ident,
    impl_generics: &syn::ImplGenerics<'_>,
    ty_generics:   &syn::TypeGenerics<'_>,
    where_clause:  Option<&syn::WhereClause>,
    appends:       &[String],
) -> TokenStream2 {
    let appends_trait_name = Ident::new(
        &format!("{}Appends", struct_name),
        struct_name.span(),
    );

    // One method declaration per appended field
    let append_methods: Vec<TokenStream2> = appends.iter().map(|field| {
        let method = Ident::new(field, Span::call_site());
        quote! { fn #method(&self) -> ::serde_json::Value; }
    }).collect();

    let appends_trait = if !appends.is_empty() {
        quote! {
            /// Generated by `#[model(appends = [...])]`. Implement to supply computed fields.
            pub trait #appends_trait_name {
                #(#append_methods)*
            }
        }
    } else { quote! {} };

    // Statements inserting appended fields into the JSON map
    let appends_insert: Vec<TokenStream2> = appends.iter().map(|field| {
        let method = Ident::new(field, Span::call_site());
        quote! { map.insert(#field.to_string(), self.#method()); }
    }).collect();

    // serialize() — needs Serialize, and AppendsTrait if appends are present
    let serialize_fn = if !appends.is_empty() {
        let t = &appends_trait_name;
        quote! {
            /// Serialize this model respecting `hidden`/`visible` rules and appended fields.
            pub fn serialize(&self) -> ::serde_json::Value
            where Self: #t + ::serde::Serialize,
            {
                let val = ::serde_json::to_value(self)
                    .unwrap_or(::serde_json::Value::Null);
                let mut map = match val {
                    ::serde_json::Value::Object(m) => m,
                    other => return other,
                };
                for col in <Self as ::rok_orm::Model>::hidden() {
                    map.remove(*col);
                }
                let vis = <Self as ::rok_orm::Model>::visible();
                if !vis.is_empty() {
                    map.retain(|k, _| vis.contains(&k.as_str()));
                }
                #(#appends_insert)*
                ::serde_json::Value::Object(map)
            }
        }
    } else {
        quote! {
            /// Serialize this model respecting `hidden`/`visible` rules.
            pub fn serialize(&self) -> ::serde_json::Value
            where Self: ::serde::Serialize,
            {
                let val = ::serde_json::to_value(self)
                    .unwrap_or(::serde_json::Value::Null);
                let mut map = match val {
                    ::serde_json::Value::Object(m) => m,
                    other => return other,
                };
                for col in <Self as ::rok_orm::Model>::hidden() {
                    map.remove(*col);
                }
                let vis = <Self as ::rok_orm::Model>::visible();
                if !vis.is_empty() {
                    map.retain(|k, _| vis.contains(&k.as_str()));
                }
                ::serde_json::Value::Object(map)
            }
        }
    };

    quote! {
        #appends_trait

        impl #impl_generics #struct_name #ty_generics #where_clause {
            #serialize_fn

            /// Temporarily reveal hidden fields for one serialization call.
            pub fn make_visible<'__s>(&'__s self, fields: &[&str])
                -> ::rok_orm::serialization::SerializeOverride<'__s, Self>
            where Self: ::serde::Serialize,
            {
                ::rok_orm::serialization::SerializeOverride::visible(self, fields)
            }

            /// Temporarily hide additional fields for one serialization call.
            pub fn make_hidden<'__s>(&'__s self, fields: &[&str])
                -> ::rok_orm::serialization::SerializeOverride<'__s, Self>
            where Self: ::serde::Serialize,
            {
                ::rok_orm::serialization::SerializeOverride::hidden(self, fields)
            }
        }
    }
}

// ── 11.3 Accessors ───────────────────────────────────────────────────────────

/// Generate `{Model}Accessors` trait and inherent `get_attribute()`.
///
/// The trait provides:
/// - `fn get_{field}(&self)` — user must implement (no default, type unknown to macro)
/// - `fn set_{field}(val: SqlValue) -> SqlValue` — default passthrough
///
/// A blanket `impl {Model}Accessors for {Model}` is NOT generated so users can
/// freely provide their own full implementation.
pub fn gen_accessors(
    struct_name:     &Ident,
    impl_generics:   &syn::ImplGenerics<'_>,
    ty_generics:     &syn::TypeGenerics<'_>,
    where_clause:    Option<&syn::WhereClause>,
    accessor_fields: &[(proc_macro2::Ident, String)],
) -> TokenStream2 {
    if accessor_fields.is_empty() {
        return quote! {};
    }

    let trait_name = Ident::new(
        &format!("{}Accessors", struct_name),
        struct_name.span(),
    );

    // Trait method signatures
    let trait_methods: Vec<TokenStream2> = accessor_fields.iter().map(|(ident, _col)| {
        let get_m = Ident::new(&format!("get_{}", ident), ident.span());
        let set_m = Ident::new(&format!("set_{}", ident), ident.span());
        quote! {
            /// Read accessor. Override to transform the value on load.
            fn #get_m(&self) -> ::rok_orm::SqlValue;
            /// Write mutator. Default passes value through unchanged.
            fn #set_m(val: ::rok_orm::SqlValue) -> ::rok_orm::SqlValue { val }
        }
    }).collect();

    // get_attribute() match arms
    let match_arms: Vec<TokenStream2> = accessor_fields.iter().map(|(ident, col)| {
        let get_m = Ident::new(&format!("get_{}", ident), ident.span());
        quote! { #col => self.#get_m(), }
    }).collect();

    quote! {
        /// Generated accessor trait for [`#struct_name`].
        ///
        /// Implement this trait to apply custom transformations on read (`get_*`)
        /// and write (`set_*`). `set_*` methods have a passthrough default.
        pub trait #trait_name {
            #(#trait_methods)*
        }

        impl #impl_generics #struct_name #ty_generics #where_clause {
            /// Return the accessor-transformed value for `col`.
            ///
            /// Requires `Self: {Model}Accessors`. Returns [`SqlValue::Null`] for
            /// columns not marked with `#[model(accessor)]`.
            pub fn get_attribute(&self, col: &str) -> ::rok_orm::SqlValue
            where Self: #trait_name,
            {
                match col {
                    #(#match_arms)*
                    _ => ::rok_orm::SqlValue::Null,
                }
            }
        }
    }
}
