version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: rok-postgres-14a
    environment:
      POSTGRES_USER: rok
      POSTGRES_PASSWORD: rokpass
      POSTGRES_DB: rok_orm_14a
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rok -d rok_orm_14a"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data:
