//! Relation metadata registry — generated by `#[derive(Relations)]`.
//!
//! Each model that derives `Relations` also gets a `RelationMeta` impl that lets
//! `QueryBuilder::where_has_named` resolve FK info by relation name at call-site.

use crate::query::QueryBuilder;

/// Provides runtime lookup of relation metadata (table + FK) by relation name.
///
/// Generated automatically by `#[derive(Relations)]`. You can also implement it manually.
///
/// # Example
///
/// ```rust
/// use rok_orm::relations::RelationMeta;
///
/// // impl RelationMeta for Post { ... } is auto-generated
/// // Post::query().where_has_named("comments", |q| q.filter("published", true))
/// ```
pub trait RelationMeta {
    /// Return `(child_table, foreign_key)` for the named relation, or `None`.
    fn relation_info(name: &str) -> Option<(&'static str, &'static str)>;
}

impl<T> QueryBuilder<T>
where
    T: RelationMeta,
{
    /// Add `WHERE EXISTS` for a named relation, resolving FK via `RelationMeta`.
    ///
    /// # Example
    ///
    /// ```rust
    /// use rok_orm::QueryBuilder;
    ///
    /// // Post implements RelationMeta with "comments" -> ("comments", "post_id")
    /// // Post::query().where_has_named("comments", |q| q.filter("published", true))
    /// ```
    pub fn where_has_named(
        self,
        relation_name: &str,
        _f: impl FnOnce(QueryBuilder<()>) -> QueryBuilder<()>,
    ) -> Self {
        if let Some((child_table, fk)) = T::relation_info(relation_name) {
            let parent_table = self.table().to_string();
            let subquery = format!("SELECT 1 FROM {child_table} WHERE {child_table}.{fk} = {parent_table}.id");
            self.where_has_raw(&subquery)
        } else {
            self
        }
    }

    /// Add `WHERE NOT EXISTS` for a named relation, resolving FK via `RelationMeta`.
    pub fn where_doesnt_have_named(self, relation_name: &str) -> Self {
        if let Some((child_table, fk)) = T::relation_info(relation_name) {
            let parent_table = self.table().to_string();
            let subquery = format!("SELECT 1 FROM {child_table} WHERE {child_table}.{fk} = {parent_table}.id");
            self.where_doesnt_have_raw(&subquery)
        } else {
            self
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::Model;

    struct Post;
    impl Model for Post {
        fn table_name() -> &'static str { "posts" }
        fn columns() -> &'static [&'static str] { &["id", "user_id", "title"] }
    }
    impl RelationMeta for Post {
        fn relation_info(name: &str) -> Option<(&'static str, &'static str)> {
            match name {
                "comments" => Some(("comments", "post_id")),
                _ => None,
            }
        }
    }

    #[test]
    fn where_has_named_generates_exists() {
        let (sql, _) = QueryBuilder::<Post>::new("posts")
            .where_has_named("comments", |q| q)
            .to_sql();
        assert!(sql.contains("EXISTS"), "sql: {sql}");
        assert!(sql.contains("comments.post_id = posts.id"), "sql: {sql}");
    }

    #[test]
    fn where_doesnt_have_named_generates_not_exists() {
        let (sql, _) = QueryBuilder::<Post>::new("posts")
            .where_doesnt_have_named("comments")
            .to_sql();
        assert!(sql.contains("NOT EXISTS"), "sql: {sql}");
        assert!(sql.contains("comments.post_id"), "sql: {sql}");
    }

    #[test]
    fn unknown_relation_is_noop() {
        let (sql1, _) = QueryBuilder::<Post>::new("posts").to_sql();
        let (sql2, _) = QueryBuilder::<Post>::new("posts")
            .where_has_named("nonexistent", |q| q)
            .to_sql();
        assert_eq!(sql1, sql2);
    }
}
